### ISSUE TITLE
Using express is a (potential and unnecessary) security issue

### ISSUE THREAD

**Issue by MarshallOfSound** [itsMapleLeaf/remix-electron#1]
Using express opens up a port on the end users machine that any application can access, even a regular web browser.  If there's any private info being served up a random website could potentially steal it or if the version of electron/node you're shipping with has another security issue in the http.Server implementation all of your users could get pwned.

To do this in a safe way we should be using Electron Custom Protocols via the `protocol` module.

Ref: https://electronjs.org/docs/latest/api/protocol

Not sure on the specifics of remix but you should be able to wire it up into a custom protocol that is substantially safer to use than a localhost server.

**Comment by itsMapleLeaf** [comment]
Thanks for bringing this up. I've never used this protocol API before, but I'll try to see if I can get it working. PRs or example implementations are also welcome :slightly_smiling_face:

**Comment by itsMapleLeaf** [comment]
I'll give some background as well: The goal here was to allow the usage of remix's `loader` and `action` APIs as a cleaner alternative to the usual electron techniques, e.g. IPC messaging and preload files. To my knowledge, that requires _some_ sort of server process, hence the node server.

I've seen the suggestion of loading the files statically via `loadFile`, but Remix is server-first; there is no static `index.html` file to load. Our content has to come from a server.

As I understand, the security issue is the node server listening on an open port, so we'll avoid that.

The problem to solve now is how to make a "fake request" to the express app that Remix runs on. Blanking out on a few pieces here:
```ts
async function main() {
  await app.whenReady()
  win = new BrowserWindow()
  
  win.loadURL(/* ??? */)

  protocol.interceptHttpProtocol("http", (request, callback) => {
    /* ??? */
  })
}
```

Or maybe there's some other completely different approach I haven't thought of :shrug: Either way, that's where I'm at.

**Comment by itsMapleLeaf** [comment]
I dug further, and Remix actually exposes apis for handling custom-crafted requests. I used that to send responses from an interception, and that seems to work, with a few other patches to fill in. Here's the PR for it https://github.com/itsMapleLeaf/remix-electron/pull/2
