### ISSUE TITLE
💡 Feature Request: add React devtools 

### ISSUE THREAD

**Issue by cliffordfajardo** [itsMapleLeaf/remix-electron#14]
## Scenario
As a `remix-electron` user, it would be nice to be able to see inspect the browser devtools and see the `react` devtools tab there.
This would allow users inspect to state of their React application once its rendered in the browser window

## Motivation for change
- save devs time from setting this ip
- help developers by enabling them to debug/inspect their React app's state etc..

![CleanShot 2022-03-04 at 02 50 12@2x](https://user-images.githubusercontent.com/6743796/156750068-154fafcb-e221-4c53-8102-79df35921fde.png)

### References
- https://www.electronjs.org/docs/latest/tutorial/devtools-extension

**Comment by itsMapleLeaf** [comment]
Yeah, I've been wanting this as well. Hopefully shouldn't be too difficult to add this in with the guide, thanks :slightly_smiling_face:
