### ISSUE TITLE
hot restart during development

### ISSUE THREAD

**Issue by sumdy-c** [itsMapleLeaf/remix-electron#15]
### Describe the bug

Hello, I won't take up your time, I'll just say that you did an amazing job, I'm thrilled with it)
The only problem I have is that I want a hot restart to work) The electron app is constantly restarting completely, I don't think this was done specifically for the convenience of development. Often the application opens a second electron window. Can you tell me if it is possible to solve this problem, because I haven't found anything in the documentation that can help me. (electron.server.ts is there).
If you need information about anything, tell me, I will answer as soon as possible!

### Minimal Reproduction

https://github.com/nope

### Steps to Reproduce the Bug or Issue

Nothing works(

### Expected behavior

Hot reboot works great

### Platform

- OS: [Linux]
- Browser: [-]
- Version: [Ubuntu 20.~]

**Comment by itsMapleLeaf** [comment]
Hi, thanks for filing this issue. For the record, I'm not actively working on Remix Electron at the moment, so PRs are open and appreciated 😊

From what I remember, I made it so the app reloads the existing window when changing browser code, but the entire electron app should reopen when changing electron code. If it's _always_ reopening regardless of what's changing, that's a bug. If it's making multiple windows, that's also a bug 😅

**Comment by sumdy-c** [comment]
Thanks for the quick response, if I can fix the problem and it is not my personal error, I will let you know the reason and offer my edits. =)
