### ISSUE TITLE
Typescript: Module remix-electron has no exported member initRemix

### ISSUE THREAD

**Issue by bmsuseluda** [itsMapleLeaf/remix-electron#26]
### Describe the bug

Hello itsMapleLeaf,

since version 2.0.0 i get the following TypeScript error with remix-electron:
`TS2305: Module "remix-electron" has no exported member initRemix`

With version 1.3.0 it worked like i would expect it.

I hope you can help me.
Thanks in regards

### Minimal Reproduction

https://github.com/bmsuseluda/emuze/blob/chore/upgradeRemix/desktop/main.ts

### Steps to Reproduce the Bug or Issue

1. yarn install
2. open `./desktop/main.ts`
3. Remove `// @ts-ignore` in first line

### Expected behavior

As with version 1.3.0 the types are exported that typescript can handle them.

### Platform

- OS: [Linux]
- typescript 5.2.2

**Comment by bmsuseluda** [comment]
i tried to fix it myself and contribute, but sadly i do not have experience with cjs

**Comment by itsMapleLeaf** [comment]
Hey, sorry for the delay. I've recently found a use case to dogfood remix-electron with, so I'll be looking into this!

**Comment by itsMapleLeaf** [comment]
This should now be fixed in 2.0.2

**Comment by bmsuseluda** [comment]
thank you it works, you are awesome :)
